export const latestPublished = [
  {
    id: 1,
    title: 'Academic Integrity Policy 2024',
    description:
      'New guidelines regarding the use of generative AI in coursework and examinations.',
    creator: 'Admin Office',
    date: '12 Oct 2023',
    type: 'REGULATION',
  },
  {
    id: 2,
    title: 'Staff Wellbeing Framework',
    description:
      'Comprehensive support systems for academic and support staff across all campuses.',
    creator: 'HR Dept',
    date: '10 Oct 2023',
    type: 'POLICY',
  },
  {
    id: 3,
    title: 'IT Resource Usage Guide',
    description: 'Standard operating procedures for accessing high-performance computing clusters.',
    creator: 'IT Services',
    date: '08 Oct 2023',
    type: 'GUIDELINE',
  },
];

export const recentlyInteracted = [
  {
    id: 1,
    title: 'Quantum Neural Networks: Analysis 2024',
    description: 'A comprehensive study on the integration of quantum computing...',
    type: 'WORD',
    edited: '2 hours ago',
  },
  {
    id: 2,
    title: 'Campus Energy Consumption Data',
    description: 'Real-time monitoring logs from all university facilities for sustainability...',
    type: 'EXCEL',
    edited: '2 hours ago',
  },
  {
    id: 3,
    title: 'Ethical Research Guidelines v4',
    description: 'Mandatory compliance document for all student researchers...',
    type: 'PDF',
    edited: '3 hours ago',
  },
  {
    id: 4,
    title: 'Ethical Research Guidelines v4',
    description: 'Mandatory compliance document for all student researchers...',
    type: 'IMAGE',
    edited: '3 hours ago',
  },
  {
    id: 5,
    title: 'Ethical Research Guidelines v4',
    description: 'Mandatory compliance document for all student researchers...',
    type: 'VIDEO',
    edited: '2 hours ago',
  },
];

export const publishedDocuments = [
  {
    id: 'MH-Admin_25-0044',
    name: 'MH-Admin_Enrollment_Form_Final_2025',
    type: 'PDF',
    status: 'APPROVED',
    creator: 'Sarah Chen',
    date: '11/12/2025 10:14 AM',
    views: 12,
    tags: ['#ACADEMIC'],
  },
  {
    id: 'Proj_Internal_Assess',
    name: 'Project_Internal_Assessment_Spreadsheet_V2',
    type: 'EXCEL',
    status: 'APPROVED',
    creator: 'Sarah Chen',
    date: '11/12/2025 10:14 AM',
    views: 12,
    tags: ['#ACADEMIC'],
  },
  {
    id: 'MH-Admin_25-0044_2',
    name: 'MH-Admin_Enrollment_Form_Final_2025',
    type: 'EXCEL',
    status: 'APPROVED',
    creator: 'Sarah Chen',
    date: '11/12/2025 10:14 AM',
    views: 12,
    tags: ['#ACADEMIC'],
  },
  {
    id: 'MH-Admin_25-0044_3',
    name: 'MH-Admin_Enrollment_Form_Final_2025',
    type: 'PDF',
    status: 'APPROVED',
    creator: 'Sarah Chen',
    date: '11/12/2025 10:14 AM',
    views: 12,
    tags: ['#ACADEMIC'],
  },
];

export const publishedDocumentsList = [
  {
    id: 1,
    type: 'PDF',
    name: 'MH-Admin_25-0044_rand... #Company Docs',
    creator: 'Admin Module',
    date: '12/12/2025',
    views: 0,
    status: 'APPROVED',
  },
  {
    id: 2,
    type: 'EXCEL',
    name: 'Project_Internal_Assessm... #Academic',
    creator: 'Admin Module',
    date: '11/12/2025',
    views: 12,
    status: 'APPROVED',
  },
  {
    id: 3,
    type: 'PDF',
    name: 'MH-Admin_Enrollment_For... #HR-Forms',
    creator: 'David Wilson',
    date: '04/12/2025',
    views: 4,
    status: 'APPROVED',
  },
  {
    id: 4,
    type: 'WORD',
    name: 'Research_Proposal_Final_... #Academic',
    creator: 'David Wilson',
    date: '01/12/2025',
    views: 28,
    status: 'PENDING',
  },
  {
    id: 5,
    type: 'WORD',
    name: 'Research_Proposal_Final_... #Academic',
    creator: 'David Wilson',
    date: '01/12/2025',
    views: 28,
    status: 'PENDING',
  },
  {
    id: 6,
    type: 'WORD',
    name: 'Research_Proposal_Final_... #Academic',
    creator: 'David Wilson',
    date: '01/12/2025',
    views: 28,
    status: 'PENDING',
  },
  {
    id: 7,
    type: 'WORD',
    name: 'Research_Proposal_Final_... #Academic',
    creator: 'David Wilson',
    date: '01/12/2025',
    views: 28,
    status: 'PENDING',
  },
  {
    id: 8,
    type: 'WORD',
    name: 'Research_Proposal_Final_... #Academic',
    creator: 'David Wilson',
    date: '01/12/2025',
    views: 28,
    status: 'PENDING',
  },
];

export const universityDepartments = [
  { name: 'Computer Science', size: '45.2 GB', files: 1500, icon: 'terminal', color: 'blue' },
  { name: 'Computer Science', size: '45.2 GB', files: 1500, icon: 'terminal', color: 'blue' },
  { name: 'Faculty of Arts', size: '12.8 GB', files: 840, icon: 'palette', color: 'red' },
  { name: 'Molecular Biology', size: '89.4 GB', files: 3200, icon: 'flask', color: 'green' },
  { name: 'Mathematics', size: '4.2 GB', files: 420, icon: 'sigma', color: 'yellow' },
];

export const universityProjects = [
  { name: 'AI Research Lab', size: '2.02 GB', members: 12, icon: 'brain', color: 'blue' },
  { name: 'Campus Sustainability', size: '856 MB', members: 5, icon: 'leaf', color: 'green' },
  { name: 'Campus Sustainability', size: '856 MB', members: 5, icon: 'leaf', color: 'green' },
  { name: 'Deep Space Initiative', size: '15.4 GB', members: 24, icon: 'rocket', color: 'purple' },
  { name: 'Archival Digitization', size: '3.1 GB', members: 8, icon: 'archive', color: 'orange' },
];

export const myHubFolders = [
  { name: 'Computer Science', size: '23.80 MB', files: 6, isPdf: false },
  { name: 'Academic Archives', size: '63.46 MB', files: 13, isPdf: false },
  { name: 'Course Materials', size: '1.39 GB', files: 14, isPdf: false },
  { name: 'Research Papers', size: '128 MB', files: 32, isPdf: false },
  { name: 'Personal Project', size: '45.2 MB', files: 4, isPdf: false },
  { name: 'Submission In...', size: '12.1 GB', files: 150, isPdf: false },
  { name: 'MHAdmin_Enrollment_Form_Final_2025', isPdf: true },
  { name: 'MHAdmin_Enrollment_Form_Final_2025', isPdf: true },
  { name: 'MHAdmin_Enrollment_Form_Final_2025', isPdf: true },
  { name: 'MHAdmin_Enrollment_Form_Final_2025', isPdf: true },
  { name: 'MHAdmin_Enrollment_Form_Final_2025', isPdf: true },
  { name: 'MHAdmin_Enrollment_Form_Final_2025', isPdf: true },
];

export const ticketMetrics = {
  total: '1,284',
  pending: '1',
  resolvedToday: '24',
  avgResponse: '2.4',
};

export const ticketList = [
  {
    id: 'MT20.000036',
    title: 'Dịch thuật văn bản pháp lý 1',
    category: 'LEGAL - Document Translation',
    status: 'PENDING',
    sender: 'Student #102',
    assignedTo: 'Sarah Jenkins',
    deadline: '30/01/2026 15:10 PM',
  },
  {
    id: 'MT20.000037',
    title: 'Thủ tục nhập học bổ sung',
    category: 'ADMISSION - Student Support',
    status: 'IN PROGRESS',
    sender: 'Staff #441',
    assignedTo: 'David Wong',
    deadline: '01/02/2026 10:00 AM',
  },
  {
    id: 'MT20.000038',
    title: 'Thủ tục nhập học bổ sung',
    category: 'ADMISSION - Student Support',
    status: 'IN PROGRESS',
    sender: 'Staff #441',
    assignedTo: 'David Wong',
    deadline: '01/02/2026 10:00 AM',
  },
  {
    id: 'MT20.000039',
    title: 'Thủ tục nhập học bổ sung',
    category: 'ADMISSION - Student Support',
    status: 'IN PROGRESS',
    sender: 'Staff #441',
    assignedTo: 'David Wong',
    deadline: '01/02/2026 10:00 AM',
  },
  {
    id: 'MT20.000040',
    title: 'Thủ tục nhập học bổ sung',
    category: 'ADMISSION - Student Support',
    status: 'IN PROGRESS',
    sender: 'Staff #441',
    assignedTo: 'David Wong',
    deadline: '01/02/2026 10:00 AM',
  },
  {
    id: 'MT20.000041',
    title: 'Thủ tục nhập học bổ sung',
    category: 'ADMISSION - Student Support',
    status: 'IN PROGRESS',
    sender: 'Staff #441',
    assignedTo: 'David Wong',
    deadline: '01/02/2026 10:00 AM',
  },
  {
    id: 'MT20.000042',
    title: 'Thủ tục nhập học bổ sung',
    category: 'ADMISSION - Student Support',
    status: 'IN PROGRESS',
    sender: 'Staff #441',
    assignedTo: 'David Wong',
    deadline: '01/02/2026 10:00 AM',
  },
];

export const ticketHistory = [
  {
    id: 1,
    user: 'Phan Gia Tâm',
    action: 'closed the ticket',
    comment: 'Ticket marked as resolved and closed.',
    time: '2025-07-31 11:45:26',
    type: 'status',
  },
  {
    id: 2,
    user: 'Phan Gia Tâm',
    action: 'added stamped Document',
    file: 'stamped_contract_final_2025.pdf',
    time: '2025-07-31 11:45:25',
    type: 'attachment',
  },
  {
    id: 3,
    user: 'Phan Gia Tâm',
    action: 'stamped Document',
    comment: 'Hợp đồng đã được đóng dấu, vui lòng liên hệ để nhận.',
    time: '2025-07-31 11:42:35',
    type: 'note',
  },
  { id: 4, user: 'Admin', action: 'approved Ticket', time: '2025-07-31 11:39:40', type: 'status' },
  {
    id: 5,
    user: 'Lý Quang Thái',
    action: 'created Ticket',
    comment: 'Note: Required file scanned',
    time: '2025-07-31 11:33:19',
    type: 'create',
  },
];

export const hubSummaryCards = [
  {
    id: 1,
    type: 'Images',
    icon: 'image',
    count: 543,
    size: '2.89 GB',
    percentage: 20,
    color: 'red',
  },
  {
    id: 2,
    type: 'Videos',
    icon: 'video',
    count: 2,
    size: '333.79 MB',
    percentage: 5,
    color: 'blue',
  },
  {
    id: 3,
    type: 'Documents',
    icon: 'document',
    count: 1235,
    size: '8.85 GB',
    percentage: 60,
    color: 'green',
  },
  {
    id: 4,
    type: 'Other',
    icon: 'archive',
    count: 226,
    size: '30.77 GB',
    percentage: 15,
    color: 'amber',
  },
];

export const recentActivity = [
  {
    id: 1,
    name: 'Thesis_Proposal_Final.pdf',
    type: 'document',
    color: 'green',
    modified: '2 hours ago',
    directory: 'Computer Science',
    owners: [
      { id: 'u1', label: 'C', color: 'orange', text: undefined },
      { id: 'u2', label: '🌿', color: 'blue', text: undefined },
    ],
  },
  {
    id: 2,
    name: 'Lab_Notes_Week_12.docx',
    type: 'document',
    color: 'amber',
    modified: 'Yesterday, 14:30',
    directory: 'AI Research Lab',
    owners: [{ id: 'u3', label: 'AT', color: 'blue', text: 'blue' }],
  },
];
